### ISSUE TITLE
where is demo data 

### ISSUE THREAD

**Issue by Jackwanguestc** [ejcgt/attention-target-detection#2]
hello ,
show in line 21 in demo.py, run demo need data/ dir, where to download?

`parser.add_argument('--image_dir', type=str, help='images', default='data/demo/frames')
parser.add_argument('--head', type=str, help='head bounding boxes', default='data/demo/person1.txt')`

**Comment by oliveiracwb** [comment]
Do you will need to implement your own recognition code. 
I used face_recorgnition with dlib. 
Fragile results, unfortunately.

**Comment by ejcgt** [comment]
Hi @Jackwanguestc sorry for missing the data! They're now added please check out the repo again.

**Comment by ejcgt** [comment]
@oliveiracwb yeah I am working on a fully automated pipleline, but currently you would have to rely on a detection/recognition module of your choice which may not be super reliable in practice unfortunately.
